const TermsOfServices = () => {
    return (
        <div className="font-secondary text-center my-10 max-w-[1000px] mx-auto">
            <h2 className="font-primary text-3xl">Terms Of Service</h2>
            <div className="mt-4 flex flex-col gap-8">
                <aside className="text-start flex flex-col gap-2">
                    <h3 className="text-xl">TERMS AND CONDITIONS</h3>
                    <p>Use of this website is subject to the following terms and conditions. Customers of the online store should also refer to the Terms of Sale. Brujhas may modify these terms from time to time, by updating this page, so that the modified terms will be effective for all users as of the date indicated on the page. Therefore, users should consult the terms frequently. By using the website, users indicate their consent and approval of these terms. If the user does not approve them, he/she should not use the website.</p>
                </aside>
                <aside className="text-start flex flex-col gap-2">
                    <h3 className="text-xl">CONSENT TO THE PROCESSING OF PERSONAL DATA</h3>
                    <div className="flex flex-col gap-4">
                        <p>In compliance with the personal data protection regulations in force, (hereinafter the Law), I grant voluntary, free, prior, express, informed and unequivocal consent to Brujhas, to carry out for an indefinite period of time, the processing, destination, flow and transfer, in any of its modalities, media or supports, local or cross-border, of the information and personal and identification data that I may have provided under any means or modality, directly or indirectly, including names, surnames, identification data, fingerprint, address, telephone numbers, e-mails, image, vehicle characteristics, service incidents, items or services of interest, preferences and preferences and services of interest, preferences and services of interest, preferences and services of interest, preferences and services of interest, preferences and services of interest, preferences and services of interest, preferences and services of interest, preferences and services of interest, preferences and services of interest, articles or services of interest, preferences and interests in general, economic, financial and insurance data, social relations, for administrative, commercial, advertising, marketing, statistical, financial, negotiation and/or contracting of products and services, monitoring of service intervals, research and development of products and services of the brand and dissemination of the image of the same, consulting, attention to claims and requests, and offers in general directly or indirectly related to the activities of Brujhas and anyone who may have any connection, or third parties with whom it maintains some kind of legal or social relationship.</p>
                        <p>The personal data collected will be incorporated and processed in a Data Bank whose existence is known to the user, which is automated and non-automated, expressly guaranteeing the technical, organizational and legal security measures for the processing, security and confidentiality of personal data provided by its customers. Security and confidentiality is also ensured for the transfer and / or cross-border flow of the same.</p>
                    </div>
                </aside>
                <aside className="text-start flex flex-col gap-2">
                    <h3 className="text-xl">MATERIAL ENVIADO POR LOS USUARIOS</h3>
                    <p>Any communication or material you transmit to the Website by electronic mail or otherwise, other than your personal data, including but not limited to data, answers or questions, comments, suggestions or the like, will be treated by Brujhas as non-confidential and non-proprietary. By submitting any communication to the Website, you automatically grant Brujhas a royalty-free, permanent, irrevocable, non-exclusive license to use, reproduce, modify, publish, edit, translate, distribute, perform and display such communication, both individually and as part of other works in any form, media, or technology, whether now known or later developed, and to sublicense such rights to anyone Brujhas deems appropriate. Any material you transmit or post may be used by Brujhas and its affiliates for any purpose, including but not limited to reproduction, disclosure, transmission, publication, broadcast and exhibition, and the development, manufacture or marketing of products using such information, except as prohibited by law.</p>
                </aside>
                <aside className="text-start flex flex-col gap-2">
                    <h3 className="text-xl">PERMITTED USES OF THE WEBSITE</h3>
                    <p>The User agrees to use the Website, its contents and services in accordance with the law, with these Terms and Conditions, with the codes of good conduct and with public order. Likewise, the User undertakes not to use the Website for illicit purposes or purposes that are contrary to the contents of these Terms and Conditions, or prejudicial to the interests or rights of third parties, or that may in any way damage, render useless or affect the Website or its services, or prevent the normal use of the Website by other users. Likewise, the User expressly undertakes not to destroy, alter, render useless or damage in any way the data, programs or electronic or other documents contained on the Website. The User undertakes not to hinder the access of other users to the registration service through the massive consumption of computer resources used by Brujhas to offer the service, and not to carry out activities that damage, alter or cause errors in such systems. The User agrees not to introduce programs, viruses, macros, applets, ActiveX controls or any other logical device or sequence of characters that cause or may cause any type of deficiency in the computer systems of Brujhas or third parties.</p>
                </aside>
                <aside className="text-start flex flex-col gap-2">
                    <h3 className="text-xl">INTELLECTUAL PROPERTY</h3>
                    <p>The entire contents of the Website (including but not limited to its graphic design, source code, logos, text, graphics, illustrations, photographs and other elements appearing on the Website), as well as any trade names, trademarks or distinctive signs of any kind appearing on the Website, are protected by law. Brujhas does not grant any license or authorization to use such content, trademarks, trade names or distinctive signs for public or commercial purposes.</p>
                </aside>
                <aside className="text-start flex flex-col gap-2">
                    <h3 className="text-xl">DECLARACIÓN CONTRA LA FALSIFICACIÓN</h3>
                    <p>At Brujhas, we are extremely concerned about counterfeiting and make constant efforts to combat it. Counterfeiting is an illegal activity with a global impact. Not only does it damage the global economy, but, even worse, it also has serious social repercussions. In fact, for example, many counterfeiters do not respect laws relating to safety, the environment or child labor (among others). Brujhas does not compromise with those who trade in counterfeit Brujhas products. Therefore, whenever necessary, we will take appropriate legal action to combat counterfeiting of Brujhas products or misuse of our brand and designs.Translated with DeepL.com (free version)</p>
                </aside>
            </div>
        </div>
    );
};

export default TermsOfServices;